[window]
opacity = 1

[font]
normal = { family = "MesloLGM Nerd Font", style = "Regular" }

# Kanagawa Alacritty Colors
[colors]
# kanagawa-dragon
primary = { background = "#181616", foreground = "#c5c9c5" }
normal = { black = "#0d0c0c", red = "#c4746e", green = "#8a9a7b", yellow = "#c4b28a", blue = "#8ba4b0", magenta = "#a292a3", cyan = "#8ea4a2", white = "#C8C093" }
bright = { black = "#a6a69c", red = "#E46876", green = "#87a987", yellow = "#E6C384", blue = "#7FB4CA", magenta = "#938AA9", cyan = "#7AA89F", white = "#c5c9c5" }
selection = { background = "#2D4F67", foreground = "#C8C093" }
indexed_colors = [ { index = 16, color = "#b6927b" }, { index = 17, color = "#b98d7b" } ]

# kanagawa-wave
# primary = { background = "0x1f1f28", foreground = "0xdcd7ba" }
# normal = { black = "0x090618", red = "0xc34043", green = "0x76946a", yellow = "0xc0a36e", blue = "0x7e9cd8", magenta = "0x957fb8", cyan = "0x6a9589", white = "0xc8c093" }
# bright = { black = "0x727169", red = "0xe82424", green = "0x98bb6c", yellow = "0xe6c384", blue = "0x7fb4ca", magenta = "0x938aa9", cyan = "0x7aa89f", white = "0xdcd7ba" }
# selection = { background = "0x2d4f67", foreground = "0xc8c093" }
# indexed_colors = [
#   { index = 16, color = "0xffa066" },
#   { index = 17, color = "0xff5d62" }
# ]

